# Generated by Django 4.1 on 2022-08-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0006_alter_day_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(help_text='Easy to remember, 20 characters max', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Easy to remember, 20 characters max', max_length=20),
        ),
    ]
