# Generated by Django 4.1 on 2022-08-20 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0007_alter_stage_name_alter_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='day',
            name='study_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='usable_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='worktime',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Time spent in school/office, may leave it 0 and update later', max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='user_day_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.CheckConstraint(check=models.Q(('time_usage_ratio__range', (0, 1))), name='day_time_usage_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_stage_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(check=models.Q(('time_usage_ratio__range', (0, 1))), name='stage_time_usage_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_subject_uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('time_usage_ratio__range', (0, 1))), name='user_time_usage_ratio_range'),
        ),
    ]
