# Generated by Django 4.1 on 2022-08-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0008_alter_user_options_alter_day_study_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='worktime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
