# Generated by Django 4.1 on 2022-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0010_alter_day_end_next_day_alter_day_worktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='end_next_day',
            field=models.BooleanField(blank=True, default=False, help_text='May be completed later', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_next_day',
            field=models.BooleanField(blank=True, default=False, help_text='May be completed later', null=True),
        ),
    ]
