# Generated by Django 4.1 on 2022-09-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0001_squashed_0014_alter_day_worktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='worktime',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='May be completed later'),
        ),
    ]
