# Generated by Django 4.1.2 on 2022-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0015_alter_day_worktime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(check=models.Q(('time_usage_ratio__range', (0, 1))), name='stage_time_usage_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('time_usage_ratio__range', (0, 1))), name='user_time_usage_ratio_range'),
        ),
    ]
