# Generated by Django 4.1.2 on 2022-10-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0016_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stage',
            name='stage_time_usage_ratio_range',
        ),
    ]
