# Generated by Django 4.1.2 on 2022-10-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0017_remove_stage_stage_time_usage_ratio_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_time_usage_ratio_range',
        ),
    ]
