# Generated by Django 4.1 on 2022-08-18 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='time_usage_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
