# Generated by Django 4.1 on 2022-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0009_alter_day_worktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='end_next_day',
            field=models.BooleanField(blank=True, help_text='May be completed later', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='worktime',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in school/office, may leave it 0 and update later'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_next_day',
            field=models.BooleanField(blank=True, help_text='May be completed later', null=True),
        ),
    ]
