# Generated by Django 4.1 on 2022-08-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tracker', '0013_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='worktime',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Time spent in school/office, may leave it 0 and update later'),
        ),
    ]
